import { useState } from 'react';
import { ArrowUpRight, FilePenLine, Focus, ImagePlus, Layers3, Search, ShieldCheck, Sparkles, X, Zap } from 'lucide-react';
import { motion } from 'framer-motion';
import { Dropzone } from '@/features/upload/Dropzone';

interface LandingProps {
  onOpenImageToPdf: () => void;
  onOpenPdfEditor: () => void;
  onOpenBlur: () => void;
}

const categories = ['All tools', 'Arrange', 'Convert', 'Polish'];

export function Landing({ onOpenImageToPdf, onOpenPdfEditor, onOpenBlur }: LandingProps) {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All tools');
  const normalizedQuery = query.trim().toLowerCase();
  const shows = (name: string, description: string, group: string) => (category === 'All tools' || category === group) && (!normalizedQuery || `${name} ${description}`.toLowerCase().includes(normalizedQuery));
  const visibleCount = [shows('Arrange for print', 'images layouts print', 'Arrange'), shows('Image to PDF', 'convert images pdf', 'Convert'), shows('Blur image', 'blur polish image', 'Polish'), shows('PDF editor', 'edit pdf', 'Convert')].filter(Boolean).length;

  return (
    <main className="mx-auto max-w-5xl px-5 py-8 sm:px-8 sm:py-12">
      <motion.header initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.25 }} className="mx-auto max-w-2xl text-center"><h1 className="text-4xl font-semibold tracking-tight text-ink dark:text-white sm:text-5xl">Your files, ready for anywhere.</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-ink-muted sm:text-base">A growing set of calm, useful tools for arranging, converting, and polishing files in your browser.</p></motion.header>

      <section className="mx-auto mt-8 max-w-3xl"><label className="flex h-12 items-center gap-3 rounded-xl border border-border bg-white px-4 shadow-card transition focus-within:border-accent focus-within:ring-2 focus-within:ring-accent/10 dark:border-dark-border dark:bg-dark-surface"><Search className="h-4 w-4 shrink-0 text-ink-faint dark:text-white/40" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tools" aria-label="Search tools" className="min-w-0 flex-1 bg-transparent text-sm text-ink outline-none placeholder:text-ink-faint dark:text-white dark:placeholder:text-white/40" />{query && <button type="button" aria-label="Clear search" onClick={() => setQuery('')} className="rounded-md p-1 text-ink-faint hover:bg-surface-muted hover:text-ink dark:text-white/40 dark:hover:bg-white/10 dark:hover:text-white"><X className="h-4 w-4" /></button>}<span className="hidden border-l border-border pl-3 text-xs text-ink-faint sm:block dark:border-dark-border dark:text-white/40">{visibleCount} tools</span></label><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={`shrink-0 rounded-full border px-3 py-1.5 text-xs font-medium transition ${category === item ? 'border-ink bg-ink text-white dark:border-white dark:bg-white dark:text-ink' : 'border-border bg-surface-muted text-ink-muted hover:border-border-strong hover:text-ink dark:border-dark-border dark:bg-dark-surface dark:text-white/70 dark:hover:border-white/30 dark:hover:text-white'}`}>{item}</button>)}</div></section>

      <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {shows('Arrange for print', 'images layouts print', 'Arrange') && <div className="rounded-2xl border border-border bg-white p-4 shadow-card dark:border-dark-border dark:bg-dark-surface"><div className="mb-4 flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-accent">Arrange</p><h2 className="mt-1 text-lg font-semibold text-ink dark:text-white">Arrange for print</h2></div><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent-subtle text-accent dark:bg-accent/15"><ImagePlus className="h-4 w-4" /></span></div><p className="mb-4 text-sm leading-5 text-ink-muted">Fit images onto clean pages with rotation, spacing, and density controls.</p><Dropzone compact /></div>}
        {shows('Image to PDF', 'convert images pdf', 'Convert') && <button type="button" onClick={onOpenImageToPdf} className="group flex min-h-[270px] flex-col rounded-2xl border border-border bg-white p-5 text-left shadow-card transition hover:-translate-y-0.5 hover:border-border-strong hover:shadow-pop dark:border-dark-border dark:bg-dark-surface"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300"><Layers3 className="h-5 w-5" /></span><ArrowUpRight className="h-4 w-4 text-ink-faint transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-accent" /></div><div className="mt-auto"><h2 className="text-lg font-semibold text-ink dark:text-white">Image to PDF</h2><p className="mt-2 text-sm leading-5 text-ink-muted">One image per A4 portrait page, with image rotation kept intact.</p><span className="mt-5 block text-xs font-semibold uppercase tracking-[0.12em] text-emerald-700 dark:text-emerald-300">Convert files</span></div></button>}
        {shows('Blur image', 'blur polish image', 'Polish') && <button type="button" onClick={onOpenBlur} className="group flex min-h-[270px] flex-col rounded-2xl border border-border bg-white p-5 text-left shadow-card transition hover:-translate-y-0.5 hover:border-border-strong hover:shadow-pop dark:border-dark-border dark:bg-dark-surface"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-100 text-cyan-700 dark:bg-cyan-400/15 dark:text-cyan-300"><Focus className="h-5 w-5" /></span><ArrowUpRight className="h-4 w-4 text-ink-faint transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-accent" /></div><div className="mt-auto"><h2 className="text-lg font-semibold text-ink dark:text-white">Blur image</h2><p className="mt-2 text-sm leading-5 text-ink-muted">Fast, private blur with live preview and adjustable strength.</p><span className="mt-5 block text-xs font-semibold uppercase tracking-[0.12em] text-cyan-700 dark:text-cyan-300">Polish an image</span></div></button>}
        {shows('PDF editor', 'edit pdf', 'Convert') && <button type="button" onClick={onOpenPdfEditor} disabled aria-label="PDF editor coming soon" className="group flex min-h-[270px] cursor-not-allowed flex-col rounded-2xl border border-border bg-white p-5 text-left opacity-60 dark:border-dark-border dark:bg-dark-surface"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-100 text-amber-700 dark:bg-amber-400/15 dark:text-amber-300"><FilePenLine className="h-5 w-5" /></span><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-amber-700 dark:bg-amber-400/10 dark:text-amber-300">Soon</span></div><div className="mt-auto"><h2 className="text-lg font-semibold text-ink dark:text-white">PDF editor</h2><p className="mt-2 text-sm leading-5 text-ink-muted">Page cleanup, rotation, naming, and export in one workspace.</p><span className="mt-5 block text-xs font-semibold uppercase tracking-[0.12em] text-amber-700 dark:text-amber-300">Coming soon</span></div></button>}
      </section>

      {visibleCount === 0 && <div className="mt-8 rounded-2xl border border-dashed border-border px-6 py-12 text-center dark:border-dark-border"><Sparkles className="mx-auto h-6 w-6 text-ink-faint" /><p className="mt-3 text-sm font-medium text-ink dark:text-white">No tools match that search.</p><button type="button" onClick={() => { setQuery(''); setCategory('All tools'); }} className="mt-3 text-xs font-semibold text-accent">Show all tools</button></div>}

      <footer className="mt-10 flex flex-col items-center justify-center gap-3 border-t border-border pt-6 text-xs text-ink-faint dark:border-dark-border sm:flex-row"><span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-3.5 w-3.5 text-emerald-600" /> Private by default</span><span className="hidden text-border sm:block">/</span><span className="inline-flex items-center gap-1.5"><Zap className="h-3.5 w-3.5" /> No upload wait</span></footer>
    </main>
  );
}
